In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("dataset_1.csv")

In [3]:
dataset.head()

x      y      z
0  0.084  0.803  0.524
1  0.311  1.644  0.532
2  0.549  2.553  0.062
3  0.249  1.584  0.321
4  0.366  1.646  0.393

In [5]:
list_x = dataset['x']
list_y = dataset['y']
list_z = dataset['z']

In [7]:
var_x = np.var(list_x)
print(var_x)
var_y = np.var(list_y)
print(var_y)
var_z = np.var(list_z)
print(var_z)

0.08052930588400004
2.0969025915190014
0.08050195487900003


In [8]:
covXY = np.cov(dataset['x'],dataset['y'])
print(covXY)

[[ 0.08060992  0.40242878]
 [ 0.40242878  2.09900159]]


In [9]:
covYZ = np.cov(dataset['y'],dataset['z'])
print(covYZ)

[[ 2.09900159 -0.01439466]
 [-0.01439466  0.08058254]]


In [13]:
def meancentric(arr,mean):
    listA = []
    for i in range(len(arr)):
        listA.append(arr[i]-mean)
    return listA 

In [12]:
means = np.mean(dataset, axis=0)

In [15]:
list_x = meancentric(dataset['x'],means[0])
list_y = meancentric(dataset['y'],means[1])
list_z = meancentric(dataset['z'],means[2])

In [16]:
dataset_1 = pd.DataFrame(columns=['x','y','z'])

In [17]:
dataset_1['x'] = list_x
dataset_1['y'] = list_y
dataset_1['z'] = list_z

In [18]:
meanCentric_matrix = dataset_1.as_matrix()

In [19]:
cov = np.cov(meanCentric_matrix.T)

In [21]:
eigenValues,eigenVectors = np.linalg.eig(cov)

In [35]:
cov_y = np.dot(eigenVectors.T,np.dot(cov,eigenVectors))

In [36]:
cov_y

array([[  2.17638133e+00,   3.21113896e-17,   2.16840434e-18],
       [  2.49637550e-17,   3.33122167e-03,   3.79470760e-19],
       [  1.73472348e-18,   1.32137140e-19,   8.04814978e-02]])

Question 3

In [37]:
A = pd.DataFrame(columns=['x','y'])

In [39]:
A["x"] = [0,2]
A["y"] = [-1,3]

In [40]:
eigenValues,eigenVectors = np.linalg.eig(A)

In [41]:
eigenValues

array([ 1.,  2.])

In [42]:
eigenVectors

array([[-0.70710678,  0.4472136 ],
       [ 0.70710678, -0.89442719]])